# Generated by Django 4.2.16 on 2024-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
